apiVersion: v1
kind: ConfigMap
metadata:
  name: opsmx-provider-config
data:
  providerConfig: |
    application: jobtest
    user: admin
    gateUrl: 'https://osi-isd.isd-qa.opsmx.net/'
    lifetimeMinutes: 3
    intervalTime: 3
    lookBackType: sliding
    gitops: false
    passScore: 90
    serviceList:
    - metricScopeVariables: "${namespace_key},${pod_key},${app_key}"
      baselineMetricScope: "isd-argofull,{{env.STABLE_POD_HASH}},issugen-baseline"
      canaryMetricScope: "isd-argofull,{{env.LATEST_POD_HASH}},issugen-baseline"
      metricTemplateName: "relicworking2"
      metricTemplateVersion: "v1.0"
    - logTemplateName: newstack
      logScopeVariables: "resource.labels.pod_name"
      baselineLogScope: ".*{{env.STABLE_POD_HASH}}.*"
      canaryLogScope: ".*{{env.LATEST_POD_HASH}}.*"
      logTemplateVersion: "v3.0"
