apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: job-analysis2
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: job-analysis2
      provider:
        job:
          spec:
            backoffLimit: 2
            template:
              spec:
                serviceAccountName: job-acc3
                imagePullSecrets:
                - name: opsmx11-secret
                containers:
                - name: job-analysis2
                  image: 'opsmx11/argo-isd-metric-provider-job:v2' 
                  imagePullPolicy: Always
                  env:
                    - name: MY_POD_NAME
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.name
                  volumeMounts:
                    - name: provider-config-volume
                      mountPath: /etc/config/provider
                    - name: metric-config-volume
                      mountPath: /etc/config/templates
                    - name: secret-config-volume
                      mountPath: /etc/config/secrets
                      readOnly: true
                restartPolicy: Never
                volumes:
                - name: provider-config-volume
                  configMap:
                    name: opsmx-provider-config3
                - name: metric-config-volume
                  configMap:
                    name: metrixtemplates3
                - name: secret-config-volume
                  secret:
                    secretName: opsmx-profile
                    optional: false
