apiVersion: v1
kind: ConfigMap
metadata:
  name: opsmx-provider-config3
data:
  providerConfig: |
    application: testanalysis12
    user: admin
    gateUrl: 'https://isd-argofull.isd-dev.opsmx.net/'
    lifetimeMinutes: 3
    gitops: false
    passScore: 30
    serviceList:
    - logTemplateName: splunktemp2
            logScopeVariables: "kubernetes.container_name"
            baselineLogScope: "oes-platform-br"
            canaryLogScope: "oes-platform-cr"
