apiVersion: v1
kind: ConfigMap
metadata:
  name: opsmx-provider-config2
data:
  providerConfig: |
    application: testanalysis12
    user: admin
    gateUrl: 'https://isd-argofull.isd-dev.opsmx.net/'
    lifetimeMinutes: 3
    intervalTime: 3
    lookBackType: sliding
    gitops: false
    passScore: 90
    serviceList:
    - logTemplateName: splunktemp2
            logScopeVariables: "kubernetes.container_name"
            baselineLogScope: "oes-platform-br"
            canaryLogScope: "oes-platform-cr"
