apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheusmetric25 
data:
  metrixtemplates: |
   {
  "filterKey": "${namespace_key},${pod_key},${app_name}",
  "data": {
    "percent_diff_threshold": "hard",
    "isNormalize": false,
    "groups": [
      {
        "metrics": [
          {
            "metricType": "ADVANCED",
            "metricWeight": 1,
            "nanStrategy": "Remove",
            "accountName": "prometheus-25",
            "riskDirection": "HigherOrLower",
            "customThresholdHigher": "10",
            "name": "sum(rate(container_cpu_usage_seconds_total{namespace=\"${namespace_key}\", pod=~\".*${pod_key}.*\", container!=\"\"}[1m]))",
            "criticality": "Normal",
            "customThresholdLower": "10",
            "watchlist": false
          }
        ],
        "group": "query1"
      }
    ]
  },
  "templateName": "prometheusmetric25",
  "isEdit": false,
  "advancedProvider": "PROMETHEUS",
  "versionNo": "v1.0"
}
