apiVersion: v1
kind: ConfigMap
metadata:
  name: opsmx-provider-config2
data:
  providerConfig: |
    application: jobappwithgitops
    user: admin
    gateUrl: https://isd-argocd.isd-dev.opsmx.net/
    lifetimeMinutes: 3
    intervalTime: 3
    lookBackType: sliding
    gitops: false
    passScore: 90
    serviceList:
    - metricScopeVariables: "${namespace_key},${pod_key},${app_name}"
      baselineMetricScope: "isd-argofull,{{env.STABLE_POD_HASH}},testanalysis"
      canaryMetricScope: "isd-argofull,{{env.LATEST_POD_HASH}},testanalysis"
      metricTemplateName: "metrixtemplates"
    - logTemplateName: newlog1
      logScopeVariables: "kubernetes.pod_name"
      baselineLogScope: ".*{{env.STABLE_POD_HASH}}.*"
      canaryLogScope: ".*{{env.LATEST_POD_HASH}}.*"
