apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: testappss
spec:
  metrics:
    - name: testappss
      provider:
        opsmx:
          profile: "opsmx-profile"
          gateUrl: https://argoqa-helm.isd-dev.opsmx.net/
          user: admin
          application: argocd-qa01-17394
          baselineStartTime: "2022-09-16T06:10:00Z"
          canaryStartTime: "2022-09-19T08:06:00Z"
          lifetimeMinutes: 6
          threshold: 
            pass: 80
            marginal: 60
          services:
          - metricTemplateName: testmetrictemplate17742
            metricScopeVariables: "variable1"
            baselineMetricScope: "service:baseapp"
            canaryMetricScope: "service:canaryapp"
            serviceName: "MetricServiceDatadog"        

