kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: testapps
spec:
  args:
    - name: preview-hash
    - name: baseline-hash
  metrics:
    - name: testapps
      count: 1
      provider:
        opsmx:
          gateUrl: https://argoqa-helm.isd-dev.opsmx.net/
          application: argocd-qa01-bluegreen-analysis-kavitha-93314
          user: admin
          lifetimeMinutes: 3
          threshold:
            pass: 80
            marginal: 60
          services:
          - metricTemplateName: prometheusbluegreenanalysis1
            metricTemplateVersion: "v1.0"
            metricScopeVariables: "namespace_key,pod_key"
            baselineMetricScope: "argocd,.*{args.baseline-hash}.*" 
            canaryMetricScope: "argocd,.*{{args.preview-hash}}.*"
            serviceName: prometheousservice
            
