kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: oes-analysis
spec:
  args:
    - name: experiment-hash
  metrics:
    - name: oes-analysis
      provider:
        opsmx:
          profile: "opsmx-profile"
          gateUrl: https://argoqa-helm.isd-dev.opsmx.net/
          application: diffscoringapp
          baselineStartTime: "2021-11-03T11:29:46.915Z"
          canaryStartTime: "2021-11-03T11:29:46.915Z" 
          user: admin
          lifetimeMinutes: 6
          threshold:
            pass: 80
            marginal: 60
          services:
          - logTemplateName: canarytemp
            logScopeVariables: "kubernetes.container_name"
            baselineLogScope: "baseapp-rest-1"
            canaryLogScope: "canaryapp-rest-1"
            serviceName: "Canary_Scoring"
          - logTemplateName: autonomous
            logScopeVariables: "kubernetes.container_name"
            baselineLogScope: "baseapp-rest-1"
            canaryLogScope: "canaryapp-rest-1"
            serviceName: "Autonomous_Scoring"
          - logTemplateName: definite
            logScopeVariables: "kubernetes.container_name"
            baselineLogScope: "baseapp-rest-1"
            canaryLogScope: "canaryapp-rest-1"
            serviceName: "Definite_Scoring"
          - logTemplateName: comprehencive
            logScopeVariables: "kubernetes.container_name"
            baselineLogScope: "baseapp-rest-1"
            canaryLogScope: "canaryapp-rest-1"
            serviceName: "Comphrehencive_Scoring"      
