apiVersion: v1
kind: ConfigMap
metadata:
  name: opsmx-provider-config
data:
  providerConfig: |
    application: testappqa1
    user: admin
    gateUrl: https://isd-argocd.isd-dev.opsmx.net/
    baselineStartTime: "2022-09-26T04:17:00.002Z"
    canaryStartTime: "2022-09-26T04:17:00.002Z""
    lifetimeMinutes: 3
    intervalTime: 3
    lookBackType: sliding
    gitops: false
    passScore: 90
    serviceList:
    - metricTemplateName: baseline
      metricScopeVariables: "app_key,pod_key"
      baselineMetricScope: "issugen-baseline,6944b5c7df"
      canaryMetricScope: "issugen-baseline,76f78f85ff"
    
