apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: testapp11236
spec:
  metrics:
    - name: testapp11236
      provider:
        opsmx:
          profile: "opsmx-profile"
          user: user2
          application: test-argo-rollout-extn-jay
          baselineStartTime: "2022-10-26T13:00:00Z"
          canaryStartTime: "2022-10-26T13:00:00Z"
          lifetimeMinutes: 30
          gitops: false
          threshold: 
            pass: 80
            marginal: 60
          services:
          - metricTemplateName: promwithagent-promtempqa
            metricScopeVariables: "job_name"
            baselineMetricScope: "baseline-redis"
            canaryMetricScope: "baseline-redis"

