kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: custommetric
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: custommetric
      count: 1
      initialDelay: 2s
      provider:
        opsmx:
          gateUrl: https://isd-argocd.isd-dev.opsmx.net/
          baselineStartTime: "2022-09-19T14:00:00Z"
          canaryStartTime: "2022-09-19T14:00:00Z"
          application: demonewrelic
          user: user2
          lifetimeMinutes: 6
          threshold:
            pass: 80
            marginal: 60
          services:
          - metricTemplateName: metrictemplateNewrelic
            metricScopeVariables: "resource.labels.container_name"
            baselineMetricScope: "oes-platform-br"
            canaryMetricScope: "oes-platform-br"
