kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: oes-analysisqa
spec:
  args:
    - name: experiment-hash
  metrics:
    - name: oes-analysisqa
      provider:
        opsmx:
          profile: "opsmx-profile"
          gateUrl: https://oes-argoqa.isd-dev.opsmx.net/
          application: logandmetricelkdd
          baselineStartTime: "2021-11-03T11:29:46.915Z"
          canaryStartTime: "2021-11-03T11:29:46.915Z" 
          user: user2
          lifetimeMinutes: 6
          threshold:
            pass: 80
            marginal: 60
          services:
          - metricTemplateName: CUSTOMDatadog
            metricScopeVariables: "variable1"
            baselineMetricScope: "service:baseapp"
            canaryMetricScope: "service:canaryapp"
            logTemplateName: RegularIsdTemp2
            logScopeVariables: "kubernetes.container_name"
            baselineLogScope: "baseapp-rest-1"
            canaryLogScope: "canaryapp-rest-1
