apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: testapp7788
spec:
  metrics:
    - name: testapp7788
      provider:
        opsmx:
          profile: "opsmx-profile"
          gateUrl: https://isd-argocd.isd-dev.opsmx.net/
          user: user2
          application: splunktestreview1
          baselineStartTime: "2022-03-08T10:46:00Z"
          canaryStartTime: "2022-03-08T10:46:00Z"
          lifetimeMinutes: 6
          gitops: false
          threshold: 
            pass: 50
            marginal: 20
          services:
          - logTemplateName: splunktemp2
            logScopeVariables: "kubernetes.container_name"
            baselineLogScope: "oes-platform-br"
            canaryLogScope: "oes-platform-cr"

