apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: testapp
spec:
  metrics:
    - name: testapp
      provider:
        opsmx:
          profile: "opsmx-profile"
          gateUrl: https://argoqa-helm.isd-dev.opsmx.net/
          user: admin
          application: stackdrivertesting1
          lifetimeMinutes: 6
          threshold: 
            pass: 80
            marginal: 60
          services:
          - logTemplateName: stacktemp1
            logScopeVariables: "resource.labels.container_name"
            baselineLogScope: "issuegen-prod"
            canaryLogScope: "issuegen-prod"

