kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: sj-analysis
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: sj-analysis
      count: 1
      initialDelay: 10s
      provider:
        opsmx:
          profile: opsmx-profile
          gateUrl: https://isd-argocd.isd-dev.opsmx.net/
          application: stackdriverlive1
          user: admin
          lifetimeMinutes: 6
          intervalTime: 3
          lookBackType: "growing"
          threshold:
            pass: 80
            marginal: 60
          globalMetricTemplate: newreliccustom
          globalLogTemplate: teststack1
          services:
          - metricScopeVariables: "app_key,pod_key"
            baselineMetricScope: "issugen-baseline,{{args.baseline-hash}}"
            canaryMetricScope: "issugen-baseline,{{args.canary-hash}}"
          - logScopeVariables: "resource.labels.pod_name"
            baselineLogScope: ".*{{args.baseline-hash}}.*"
            canaryLogScope: ".*{{args.canary-hash}}.*"
