kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: dctest1100
spec:
  args:
    - name: experiment-hash
  metrics:
    - name: dctest1100
      provider:
        opsmx:
          profile: "opsmx-profile"
          gateUrl: https://obs411.aoa.oes.opsmx.org/
          application: rajuelkapp1
          baselineStartTime: "2021-11-03T11:29:46.915Z"
          canaryStartTime: "2021-11-03T11:29:46.915Z" 
          user: admin
          lifetimeMinutes: 6
          gitops: false
          threshold:
            pass: 80
            marginal: 60
          services:
          - logTemplateName: logtemplatetest11
            logScopeVariables: "kubernetes.container_name"
            baselineLogScope: "baseapp-rest-1"
            canaryLogScope: "canaryapp-rest-1"
