apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: dcargo1100
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: dcargo1100
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus_io_path: '/mgmt/prometheus'
        prometheus_io_port: '8088'    
      labels:
        app: dcargo1100
    spec:
      containers:
        - name: rollouts-baseline
          image: docker.io/opsmxdev/issuegen:v3.0.7
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 2s }
        - experiment:
            templates:
              - name: baseline
                specRef: stable
              - name: canary
                specRef: canary
            analyses:
              - name : dctest1100
                requiredForCompletion: true
                templateName: dctest1100
                args:
                  - name: experiment-hash
                    valueFrom:
                      podTemplateHashValue: Latest
        - setWeight: 60
        - pause: { duration: 60s }
        - experiment:
            templates:
              - name: baseline
                specRef: stable
              - name: canary
                specRef: canary
            analyses:
              - name : dctest1100
                requiredForCompletion: true
                templateName: dctest1100
                args:
                  - name: experiment-hash
                    valueFrom: 
                      podTemplateHashValue: Latest
        - setWeight: 90
