kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: testanalysis1200
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: canary-score
      count: 1
      initialDelay: 10s    
      provider:
        opsmx:
          profile: opsmx-profile
          application: testrolloutanalysis1
          user: user2
          lifetimeMinutes: 3
          gitops: true
          threshold:
            pass: 60
            marginal: 40   
          services:
          - metricTemplateName: "promtemp12"
            metricScopeVariables: "job_name"
            baselineMetricScope: "baseline-redis"
            canaryMetricScope: "baseline-redis"
