apiVersion: argoproj.io/v1alpha1 # Create a rollout resource
kind: Rollout
metadata:
  name: nginx-rollout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  workloadRef: # Reference an existing Deployment using workloadRef field
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  strategy:
    blueGreen:
      autoPromotionEnabled: true
      activeService: nginx-stable
      previewService: nginx-preview
      prePromotionAnalysis:
        templates:
          - templateName: nginx-template
        args:
          - name: baseline-hash
            valueFrom:
              podTemplateHashValue: Stable
          - name: preview-hash
            valueFrom:
              podTemplateHashValue: Latest
          - name: servicename
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
