apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: testgraylog1
spec:
  metrics:
    - name: testgraylog1
      provider:
        opsmx:
          profile: "opsmx-profile"
          gateUrl: https://isd-argocd.isd-dev.opsmx.net/
          user: user2
          application: graylogtesting1
          baselineStartTime: "2022-02-07T08:15:37Z"
          canaryStartTime: "2022-02-07T08:15:37Z"
          lifetimeMinutes: 6
          threshold: 
            pass: 80
            marginal: 60
          services:
          - logTemplateName: graylogtemp
            logScopeVariables: "container_name"
            baselineLogScope: "oes-platform-br"
            canaryLogScope: "oes-platform-cr"

