apiVersion: v1
kind: ConfigMap
metadata:
  name: opsmx-provider-config
data:
  providerConfig: |
    gateUrl: https://isd-argofull.isd-dev.opsmx.net/
    application: newreliclive
    user: admin
    baselineStartTime: "{{args.start-time}}"
    canaryStartTime: "{{args.start-time}}"
    endTime: "{{args.end-time}}"
    threshold:
      pass: 80
      marginal: 60
    services:
    - metricTemplateName: newrelic-validator1
      metricTemplateVersion: "v2.0"
      metricScopeVariables: "${app_key},${host_key}"
      baselineMetricScope: "issuegen-exp-ss1-app1,nr-isd-exp-ss1-baseline.*"
      canaryMetricScope: "issuegen-exp-ss1-app2,nr-isd-exp-ss1-canary.*"
    - logTemplateName: newstack
      logScopeVariables: "resource.labels.pod_name"
      baselineLogScope: ".*{{env.STABLE_POD_HASH}}.*"
      canaryLogScope: ".*{{env.LATEST_POD_HASH}}.*"
      logTemplateVersion: "v1.0"
