apiVersion: v1
kind: ConfigMap
metadata:
  name: opsmx-provider-config
data:
  providerConfig: |
    application: perf-application1
    user: admin
    gateUrl: 'https://osi-isd.isd-qa.opsmx.net/'
    lifetimeMinutes: 3
    intervalTime: 3
    lookBackType: sliding
    gitops: false
    passScore: 90
    serviceList:
    - logTemplateName: perf-logtemplate
      logScopeVariables: "resource.labels.pod_name"
      baselineLogScope: ".*{{env.STABLE_POD_HASH}}.*"
      canaryLogScope: ".*{{env.LATEST_POD_HASH}}.*"
      logTemplateVersion: "v1.0"
