apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: argotest1105
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: argotest1105
  template:
    metadata:   
      labels:
        app: argotest1105
    spec:
      containers:
        - name: rollouts-demo-exp
          image: docker.io/opsmxdev/issuegen:v3.0.8
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: { duration: 45s }
        - experiment:
            analyses:
              - name : testapp1105
                requiredForCompletion: true
                templateName: testapp1105
            templates:
              - name: baseline
                specRef: stable
              - name: canary
                specRef: canary
        - setWeight: 50
        - pause: { duration: 45s }
        - experiment:
            analyses:
              - name : testapp1105
                requiredForCompletion: true
                templateName: testapp1105
            templates:
              - name: baseline
                specRef: stable
              - name: canary
                specRef: canary
