apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: testapp1103
spec:
  metrics:
    - name: testapp1103
      provider:
        opsmx:
          profile: "opsmx-profile"
          gateUrl: https://oes-argoqa.isd-dev.opsmx.net/
          user: user2
          application: metricgitops1100
          baselineStartTime: "2022-10-26T13:00:00Z"
          canaryStartTime: "2022-10-26T13:00:00Z"
          lifetimeMinutes: 30
          threshold: 
            pass: 80
            marginal: 60
          services:
          - metricTemplateName: promtemp12
            metricScopeVariables: "job_name"
            baselineMetricScope: "baseline-redis"
            canaryMetricScope: "baseline-redis"
