apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: testrollout1200
spec:
  replicas: 1
  strategy:
    canary:
      canaryService: tmpl-gitops-canary-svc
      stableService: tmpl-gitops-stable-svc
      trafficRouting:
        nginx:
          stableIngress: tmpl-gitops-ing 
      steps:
      - setWeight: 50
      - pause: { duration: 30s }
      - analysis:
          templates:
            - templateName: testanalysis1200
          args:
            - name: canary-hash
              valueFrom:
                podTemplateHashValue: Latest
            - name: baseline-hash
              valueFrom:
                podTemplateHashValue: Stable
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: testrollout1200
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus_io_path: '/mgmt/prometheus'
        prometheus_io_port: '8088'
      labels:
        app: testrollout1200
    spec:
      containers:
        - name: rollouts-demo-exp
          image: docker.io/opsmxdev/issuegen:v3.0.6
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: { duration: 45s }
        - experiment:
            analyses:
              - name : testapp1104
                requiredForCompletion: true
                templateName: testapp1104
            templates:
              - name: baseline
                specRef: stable
              - name: canary
                specRef: canary
        - setWeight: 50
        - pause: { duration: 45s }
        - experiment:
            analyses:
              - name : testapp1104
                requiredForCompletion: true
                templateName: testapp1104
            templates:
              - name: baseline
                specRef: stable
              - name: canary

