kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: tmpl-gitops
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: canary-score
      count: 1
      initialDelay: 10s    
      provider:
        opsmx:
          profile: opsmx-profile-new
          application: splunklogtest
          baselineStartTime: "2022-03-08T10:46:00Z"
          canaryStartTime: "2022-03-08T10:46:00Z"
          user: user2
          lifetimeMinutes: 3
          gitops: true
          threshold:
            pass: 60
            marginal: 40   
          services:
           - logTemplateName: logtemplate-01
             logScopeVariables: "kubernetes.container_name"
             baselineLogScope: "oes-platform-br"
             canaryLogScope: "oes-platform-cr"
