apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: testapp
spec:
  metrics:
    - name: testapp
      provider:
        opsmx:
          profile: "opsmx-profile"
          gateUrl: http://localhost:8080/
          user: admin
          application: testapp12
          baselineStartTime: "2022-08-20T13:15:00Z"
          lifetimeMinutes: 6
          threshold: 
            pass: 80
            marginal: 60
          services:
          - metricTemplateName: promtemp12
            metricScopeVariables: "job_name"
            baselineMetricScope: "baseline-redis"
            canaryMetricScope: "baseline-redis"

