kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: oes-analysis
spec:
  args:
    - name: experiment-hash
  metrics:
    - name: oes-analysis
      count: 1
      provider:
        opsmx:
          gateUrl: https://oes-argoqa.isd-dev.opsmx.net/
          application: stackappbyqa1
          baselineStartTime: "2022-09-16T06:10:00Z"
          canaryStartTime: "2022-09-19T08:06:00Z" 
          user: user2
          lifetimeMinutes: 6
          threshold:
            pass: 80
            marginal: 60
          services:
          - serviceName: service1
            logTemplateName: teststack2
            logScopeVariables: "resource.labels.container_name"
            baselineLogScope: "issuegen-prod"
            canaryLogScope: "issuegen-prod"
