kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: isd-analysis-bg-post
spec:
  args:
    - name: preview-hash
    - name: baseline-hash
  metrics:
    - name: isd-analysis-bg-post
      count: 1
      provider:
        opsmx:
          gateUrl: https://argoqa-helm.isd-dev.opsmx.net/
          application: bluegreenrollout
          user: admin
          lifetimeMinutes: 3
          baselineStartTime: "2022-11-10T16:58:48.722Z"
          threshold:
            pass: 80
            marginal: 60
          services:
          - serviceName: 
            logTemplateName: mkrlogtemp
            logScopeVariables: "kubernetes.container_name"
            baselineLogScope: "baseapp-rest-1"
            canaryLogScope: "canaryapp-rest-1"
