kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: isd-analysis-bg-post
spec:
  args:
    - name: preview-hash
    - name: baseline-hash
  metrics:
    - name: isd-analysis-bg-post
      count: 1
      provider:
        opsmx:
          gateUrl: https://argoqa-helm.isd-dev.opsmx.net/
          application: bluegreen
          user: admin
          lifetimeMinutes: 3
          baselineStartTime: "2021-11-03T11:29:46.915Z"
          threshold:
            pass: 80
            marginal: 60
          services:
          - serviceName: 
            metricTemplateName: prometheusbluegreenanalysis
            metricScopeVariables: "namespace_key,pod_key"
            baselineMetricScope: "argocd,.*{{args.baseline-hash}}.*" 
            canaryMetricScope: "argocd,.*{{args.preview-hash}}.*
