apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: testapp1234
spec:
  metrics:
    - name: testapp1234
      provider:
        opsmx:
          profile: "opsmx-profile"
          gateUrl: https://oes-argoqa.isd-dev.opsmx.net/
          user: user2
          application: gittempduptest1
          baselineStartTime: "2022-03-08T10:46:00Z"
          canaryStartTime: "2022-03-08T10:46:00Z"
          lifetimeMinutes: 6
          gitops: true
          threshold: 
            pass: 30
            marginal: 20
          services:
          - logTemplateName: logtemplatetest11
            logScopeVariables: "kubernetes.container_name"
            baselineLogScope: "oes-platform-br"
            canaryLogScope: "oes-platform-cr"

