apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: testapps
spec:
  metrics:
    - name: testapps
      provider:
        opsmx:
          profile: "opsmx-profile"
          gateUrl: https://argoqa-helm.isd-dev.opsmx.net/
          user: admin
          application: argocd-qa01-22459
          baselineStartTime: "2021-11-03T11:29:46.915Z"
          canaryStartTime: "2021-11-03T11:29:46.915Z"
          lifetimeMinutes: 6
          threshold: 
            pass: 80
            marginal: 60
          services:
          - metricTemplateName: metricTemplateDatadog01
            metricScopeVariables: "variable1"
            baselineMetricScope: "service:baseapp"
            canaryMetricScope: "service:canaryapp"
            serviceName: "MetricServiceDatadog1"
          - metricTemplateName: metrictemplateNewrelic
            metricScopeVariables: "app_key,pod_key"
            baselineMetricScope: "issugen-baseline,6944b5c7df"
            canaryMetricScope: "issugen-baseline,76f78f85ff"            
            serviceName: "MetricServiceNewRelic01"
